Implement Header
JuliaSemaka/pointing-poker pull request #11
Opened 2021-09-07 07:58 UTC by Maxfri

1. Implement Header https://github.com/JuliaSemaka/pointing-poker/issues/10
2. Screenshot: 
2.1  Default: 
![image](https://user-images.githubusercontent.com/47328756/132307182-ec582b85-c007-47f3-836e-21c00b40ede2.png)

2021-09-07 17:29 UTC, YekaterinaKarakulina requested changes
Реквест создаем в девелоп ветку, и не забываем сами просмотреть измененные файлы

2021-09-07 17:49 UTC, YekaterinaKarakulina commented on src/components/Header/Header.tsx
> +        </div>
а линтер нам не разрешает самозакрывающиеся теги использовать?

2021-09-08 21:14 UTC, JuliaSemaka approved these changes

2021-09-09 13:13 UTC, YekaterinaKarakulina approved these changes

2021-09-09 13:17 UTC, merged