Implement UI Switch
JuliaSemaka/pointing-poker pull request #34
Opened 2021-09-11 23:48 UTC by Maxfri

1. Implement UI Switch https://github.com/JuliaSemaka/pointing-poker/issues/26
2.1 Toggle off
![image](https://user-images.githubusercontent.com/47328756/132966221-20691954-1650-4607-aa87-a798658da1a1.png)
2.2
![image](https://user-images.githubusercontent.com/47328756/132966235-079cff29-3571-444a-994e-64ef54b51e1f.png)

2021-09-12 13:44 UTC, YekaterinaKarakulina requested changes

2021-09-12 13:44 UTC, YekaterinaKarakulina commented on src/App.scss
> +.wrapper {
почему здесь появились эти стили? это же Юля писала в своем ПР

2021-09-12 13:44 UTC, YekaterinaKarakulina commented on src/components/UI/Switch/Switch.tsx
> +  const { check, label } = props;
Давай сделаем так:
компонент будет принимать 3 пропса isChecked, handleClick  и label.
Стейт хранить внутри компонента не будем - он будет в родительском компоненте. 

В твоем случае в сторис нужно создать родительский компонент со стейтом и передавать пропсами в Switch стейт и функцию, меняющую стейт

2021-09-12 23:04 UTC, Maxfri commented on src/App.scss
> +.wrapper {
Я просто запулил к себе изменения

2021-09-12 23:04 UTC, Maxfri commented on src/components/UI/Switch/Switch.tsx
> +  const { check, label } = props;
Сделал

2021-09-13 10:21 UTC, YekaterinaKarakulina commented on src/App.scss
> +.wrapper {
Есть ты подтянул к себе девелоп ветку, то такого не должно быть

2021-09-13 10:22 UTC, YekaterinaKarakulina requested changes
Подтяни пожалуйста ещё раз девелоп ветку в свою. А так по коду все отлично

2021-09-13 18:21 UTC, closed without merging