Feature/UI input
JuliaSemaka/pointing-poker pull request #36
Opened 2021-09-13 10:16 UTC by JuliaSemaka

Button big:
![image](https://user-images.githubusercontent.com/12410639/133277367-4ce50af3-6021-4f30-8d31-cd4d2fc476e4.png)
Button with Button:
![image](https://user-images.githubusercontent.com/12410639/133164869-da0a1f19-17f9-4c71-80c6-fb0a563e2177.png)
Disabled button with Button:
![image](https://user-images.githubusercontent.com/12410639/133277408-257c9987-359c-4324-b250-c0b575b4c810.png)
File Input:
![image](https://user-images.githubusercontent.com/12410639/133277471-02f0b1f7-e654-4d19-8cd4-2b85aa0e6e8d.png)
Input middle:
![image](https://user-images.githubusercontent.com/12410639/133164924-c4a57545-2a3b-49fa-8ffb-e7de199699f4.png)

2021-09-13 10:19 UTC, YekaterinaKarakulina requested changes

2021-09-13 10:19 UTC, YekaterinaKarakulina commented on src/components/UI/ui.module.ts
> +  widthButton = 'with-button',
withButton

2021-09-13 10:19 UTC, YekaterinaKarakulina commented on src/components/UI/Input/Input.tsx
> +  isChange,
onChange 
is не подходит по названию. Так называют булевские переиенные

2021-09-13 10:40 UTC, JuliaSemaka commented on src/components/UI/ui.module.ts
> +  widthButton = 'with-button',
я просто сразу подставляю так в стили, по этому через дефис написали, надо исправлять? просто будет сложнее тогда названия классов для каждого енама прописывать, а так оно подставляется из этого енама.

2021-09-13 10:44 UTC, JuliaSemaka commented on src/components/UI/Input/Input.tsx
> +  isChange,
Согласна, изменила

2021-09-13 10:46 UTC, YekaterinaKarakulina commented on src/components/UI/ui.module.ts
> +  widthButton = 'with-button',
Я не про дефис , а про букву "d" в слове with

2021-09-13 10:46 UTC, YekaterinaKarakulina commented on src/components/UI/ui.module.ts
> +  widthButton = 'with-button',
Просто сам enum

2021-09-13 10:58 UTC, JuliaSemaka commented on src/components/UI/ui.module.ts
> +  widthButton = 'with-button',
А) ок

2021-09-13 11:36 UTC, YekaterinaKarakulina approved these changes

2021-09-14 04:56 UTC, YekaterinaKarakulina requested changes

2021-09-14 04:56 UTC, YekaterinaKarakulina commented on src/components/UI/RenderField/RenderField.stories.tsx
> +        <RenderField {...propsText} />
`<Field
        name="username"
        type="text"
        component={renderField}
        label="Username"
      />`

2021-09-14 14:33 UTC, JuliaSemaka commented on src/components/UI/RenderField/RenderField.stories.tsx
> +        <RenderField {...propsText} />
исправила

2021-09-14 15:01 UTC, Maxfri approved these changes

2021-09-14 15:04 UTC, YekaterinaKarakulina requested changes

2021-09-14 15:04 UTC, YekaterinaKarakulina commented on src/components/UI/RenderField/RenderField.stories.tsx
> +    <>
Здесь лишние фрагменты

2021-09-14 15:04 UTC, YekaterinaKarakulina commented on src/components/UI/RenderField/RenderField.stories.tsx
> +    <Field name="name1" component={RenderField} label="name1" {...props} />
И давай заодно название заменим name1 на testName или firstName

2021-09-14 16:30 UTC, JuliaSemaka commented on src/components/UI/RenderField/RenderField.stories.tsx
> +    <>
убрала

2021-09-14 16:31 UTC, JuliaSemaka commented on src/components/UI/RenderField/RenderField.stories.tsx
> +    <Field name="name1" component={RenderField} label="name1" {...props} />
исправила

2021-09-14 16:40 UTC, YekaterinaKarakulina approved these changes

2021-09-14 16:41 UTC, merged