Feature/UI cards
JuliaSemaka/pointing-poker pull request #44
Opened 2021-09-15 18:29 UTC by JuliaSemaka

Добавила таймер
![image](https://user-images.githubusercontent.com/12410639/133512214-8491f321-c2a4-4700-ad20-16a47a2a82c9.png)
![image](https://user-images.githubusercontent.com/12410639/133512257-0868395a-cfc5-4ad1-8c3c-f0b2ad7d99dc.png)

![image](https://user-images.githubusercontent.com/12410639/133405815-a87533df-48ad-48e8-8ac9-e09a4f2f1ab0.png)
![image](https://user-images.githubusercontent.com/12410639/133405840-de0ad451-e488-4546-b975-4d23595c5b1d.png)
![image](https://user-images.githubusercontent.com/12410639/133405882-991b79bf-d918-426c-86aa-de54448638f6.png)

![image](https://user-images.githubusercontent.com/12410639/133405917-8380cfd8-22d7-48f0-b7fc-b4f37356128a.png)
![image](https://user-images.githubusercontent.com/12410639/133503675-60505b3b-45da-46d9-9a91-0c0e527c56b8.png)
![image](https://user-images.githubusercontent.com/12410639/133503705-c0055ba9-7e6e-41fb-8c3a-780b94cb635f.png)
![image](https://user-images.githubusercontent.com/12410639/133503741-6fb3b53c-fed5-4df4-bc42-6ad68a8ea9f3.png)

2021-09-15 18:49 UTC, YekaterinaKarakulina requested changes

2021-09-15 18:49 UTC, YekaterinaKarakulina commented on src/components/UI/Cards/GameCard/GameCard.tsx
> +      )}
Юль, давай здесь тренарник заюзаем . так как здесь альтернативное условие по scoreType

2021-09-15 18:49 UTC, YekaterinaKarakulina commented on src/components/UI/Cards/IssueCard/IssueCard.tsx
> +      )}
вот эти условия с 21 по 32 строчку лучше вынести выше как константу
const cardEditorContent = ..... и можно switch case использовать, так как проверяется type на различные значения

а далее сам компонент IssueCard будет возвращать 
```
return (
<div className="card">
.....
 <div className="card-editor">
{cardEditorContent}
</div>
.....
</div>
)
```

2021-09-15 18:49 UTC, YekaterinaKarakulina commented on src/components/UI/Cards/MemberCard/MemberCard.tsx
> +      )}
17-21 строки тоже лучше вынести в константу

2021-09-15 19:52 UTC, JuliaSemaka commented on src/components/UI/Cards/GameCard/GameCard.tsx
> +      )}
сделала

2021-09-15 20:17 UTC, JuliaSemaka commented on src/components/UI/Cards/MemberCard/MemberCard.tsx
> +      )}
Вынесла в ф-ю

2021-09-15 20:17 UTC, JuliaSemaka commented on src/components/UI/Cards/IssueCard/IssueCard.tsx
> +      )}
Вынесла в ф-ю

2021-09-16 08:00 UTC, YekaterinaKarakulina approved these changes

2021-09-16 10:10 UTC, merged