Implement "Main page(unauthorized)"
JuliaSemaka/pointing-poker pull request #45
Opened 2021-09-15 23:32 UTC by Maxfri

1. Implement "Main page(unauthorized)" https://github.com/JuliaSemaka/pointing-poker/issues/3
2. Screenshot: 
2.1  Empty: 
![image](https://user-images.githubusercontent.com/47328756/133881770-b9bb7e1e-80ae-4412-a1be-9a7bd1725d72.png)
2.2 Fill valid ID 
![image](https://user-images.githubusercontent.com/47328756/133881890-d2740ae1-8e82-4620-b1f3-a3f92c75fc79.png)
2.3 Fill invalid ID
![image](https://user-images.githubusercontent.com/47328756/133882172-0137b815-5024-497f-9abe-b20da9f4cf37.png)

2021-09-15 23:38 UTC, Maxfri commented
Создал ещё раз новую ветку и сделал новый пул реквест, потому что в старом добавлялось много лишних файлов. Есть вопросы по UI компонентам, инпутам и кнопкам. В инпуте не хватает {...other} чтобы можно было свои пропсы добавлять, из за этого нельзя прокинуть пропсами валидацию (ну или я что то не понял). У кнопки есть isClick, думаю это не совсем коректно, потому что isClick подразумевает под собой что это булева переменная которая хранит значение кликнули по кнопке или нет, а у нас это пропс который передается потом в onClick. А предположим у нас в формочке кнопка должна иметь type="submit"? Мне не понятно что на неё вешать и как быть.

2021-09-17 18:10 UTC, YekaterinaKarakulina requested changes
1. Между "create session" и кнопкой "start new game" отсутствует отступ
2. OR не отцентровано
3. Отсутствует пробел в строке: Connect to lobby byID:

+ замечания по коду

2021-09-17 18:10 UTC, YekaterinaKarakulina commented on src/pages/MainPage/MainPage.tsx
> +              name="name1"
нужно дать осознанное имя для филды

2021-09-17 18:10 UTC, YekaterinaKarakulina commented on src/pages/MainPage/MainPage.tsx
> +              validate={[isRequired]}
добавить валидацию на не верное значение. Здесь надо уточнить у Юли @JuliaSemaka  какие будут id - строки или цифры. и после этого добавить валидацию

2021-09-17 18:10 UTC, YekaterinaKarakulina commented on src/pages/MainPage/MainPage.tsx
> +              placeholder="Type lobby ID"
плейсхолдер не отображается в сторис empty

2021-09-17 18:10 UTC, YekaterinaKarakulina commented on src/pages/MainPage/MainPage.stories.tsx
> +  .add('Main page unauthorized - Right Id', () => (
valid id

2021-09-17 18:10 UTC, YekaterinaKarakulina commented on src/pages/MainPage/MainPage.stories.tsx
> +  .add('Main page unauthorized - Wrong Id', () => (
invalid id. по поводу данной проверки описала комментарий ниже

2021-09-17 18:10 UTC, YekaterinaKarakulina commented on src/pages/MainPage/MainPage.stories.tsx
> +    name1: ''
name1 везжде заменить на осознанное название филды

2021-09-18 00:17 UTC, Maxfri commented on src/pages/MainPage/MainPage.tsx
> +              name="name1"
поменял на lobbyId

2021-09-18 00:17 UTC, Maxfri commented on src/pages/MainPage/MainPage.tsx
> +              validate={[isRequired]}
добавил проверку isNumber, по примеру из документации redux form

2021-09-18 00:18 UTC, Maxfri commented on src/pages/MainPage/MainPage.tsx
> +              placeholder="Type lobby ID"
добавил placeholder в компонент RenderField

2021-09-18 00:18 UTC, Maxfri commented on src/pages/MainPage/MainPage.stories.tsx
> +  .add('Main page unauthorized - Right Id', () => (
исправил

2021-09-18 00:18 UTC, Maxfri commented on src/pages/MainPage/MainPage.stories.tsx
> +  .add('Main page unauthorized - Wrong Id', () => (
исправил

2021-09-18 00:18 UTC, Maxfri commented on src/pages/MainPage/MainPage.stories.tsx
> +    name1: ''
поменял

2021-09-19 14:44 UTC, YekaterinaKarakulina requested changes

2021-09-19 14:44 UTC, YekaterinaKarakulina commented on src/pages/MainPage/MainPage.stories.tsx
> +    <>
Лишний фрагмент

2021-09-19 14:44 UTC, YekaterinaKarakulina commented on src/pages/MainPage/MainPage.tsx
> +const isNumber: ValidationFunc<any> = value => value && isNaN(Number(value)) ? 'Must be a number' : undefined
Почему number? Юля же скидывала пример id

2021-09-19 15:37 UTC, Maxfri commented on src/pages/MainPage/MainPage.tsx
> +const isNumber: ValidationFunc<any> = value => value && isNaN(Number(value)) ? 'Must be a number' : undefined
поменял

2021-09-19 15:37 UTC, Maxfri commented on src/pages/MainPage/MainPage.stories.tsx
> +    <>
удалил

2021-09-20 02:30 UTC, YekaterinaKarakulina approved these changes

2021-09-20 08:01 UTC, JuliaSemaka approved these changes

2021-09-20 09:18 UTC, merged