Feature/modal kick player
JuliaSemaka/pointing-poker pull request #47
Opened 2021-09-16 12:49 UTC by IvanYatsko

Implement "Kick player Modal":
![image](https://user-images.githubusercontent.com/50986935/133614740-d04cc5cc-5db0-46c8-ad79-c9fa6bde95bb.png)
![image](https://user-images.githubusercontent.com/50986935/133803277-6791f993-46fd-4c51-a4d5-779d3ea9f5a6.png)
![image](https://user-images.githubusercontent.com/50986935/133803312-e841962c-c260-4bad-b492-b319b401132c.png)

2021-09-16 17:12 UTC, YekaterinaKarakulina requested changes

2021-09-16 17:12 UTC, YekaterinaKarakulina commented on src/components/ModalKickPlayer/ModalKickPlayer.tsx
> +        <Button text="Yes" clickButton={func} />
не clickButton, а   handleClick

2021-09-16 17:12 UTC, YekaterinaKarakulina commented on src/components/ModalKickPlayer/ModalKickPlayer.tsx
> +  };
и эта функция должна приходить из пропсов. даже 2 на клик по кнопке да и нет. Эти функции лучге назвать onClickYes, onClickNo

2021-09-16 17:12 UTC, YekaterinaKarakulina commented on src/components/ModalKickPlayer/ModalKickPlayer.tsx
> +export const ModalKickPlayer: React.FC<IModalKickPlayer> = ({ playerName }) => {
и давай заодно компонент переименуем и сторис и папку и интерфейс )
KickPlayerModal

2021-09-17 14:39 UTC, IvanYatsko commented on src/components/ModalKickPlayer/ModalKickPlayer.tsx
> +        <Button text="Yes" clickButton={func} />
исправил

2021-09-17 14:40 UTC, IvanYatsko commented on src/components/ModalKickPlayer/ModalKickPlayer.tsx
> +  };
исправил

2021-09-17 14:40 UTC, IvanYatsko commented on src/components/ModalKickPlayer/ModalKickPlayer.tsx
> +export const ModalKickPlayer: React.FC<IModalKickPlayer> = ({ playerName }) => {
исправил

2021-09-17 18:20 UTC, JuliaSemaka approved these changes

2021-09-17 18:38 UTC, YekaterinaKarakulina requested changes
модалка совсем никак не закрывается + комментарий в коде оставила

2021-09-17 18:38 UTC, YekaterinaKarakulina commented on src/components/KickPlayerModal/KickPlayerModal.tsx
> +  return (
здесь можно не писать {}
а сразу круглые - то есть сразу возвращать jsx

2021-09-20 11:03 UTC, IvanYatsko commented on src/components/KickPlayerModal/KickPlayerModal.tsx
> +  return (
исправил

2021-09-20 11:09 UTC, JuliaSemaka approved these changes

2021-09-20 12:23 UTC, Maxfri approved these changes

2021-09-20 12:24 UTC, merged