Feature/lobby
JuliaSemaka/pointing-poker pull request #49
Opened 2021-09-17 10:10 UTC by JuliaSemaka

![image](https://user-images.githubusercontent.com/12410639/133864113-731408cb-82f4-43ad-946f-f7f9029700a8.png)
![image](https://user-images.githubusercontent.com/12410639/133864124-537c2a9b-fd78-4263-b395-7400f3e23125.png)
![image](https://user-images.githubusercontent.com/12410639/133864138-549667bc-c2f5-4306-a3f6-bae3e57d3c1f.png)

2021-09-17 18:31 UTC, YekaterinaKarakulina requested changes

2021-09-17 18:31 UTC, YekaterinaKarakulina commented on src/components/Lobby/Chat/Chat.tsx
> +        <MemberCard
в этом компоненте не должно быть захардкоженных сообщений. он должен пропсами получать массив объектов-сообщений. у каждого объекта сооющений ьудет текст и какая-то инфа об авторе сообщения.
и компонент чат просто мапом отрисовывает эти сообщения.

хотелось бы видеть сторис для данного компонента с 2 случаями: сообщения есть, массив сообщений пуст

2021-09-17 18:31 UTC, YekaterinaKarakulina commented on src/components/Lobby/GameData/GameData.tsx
> +          Spring 23 planning (issues 13, 533, 5623, 3252, 6623, ...)
опять же все захардкожено. все эти данные должны приходить пропсами
в данном случае это название + список карточек

2021-09-17 18:31 UTC, YekaterinaKarakulina commented on src/components/Lobby/GameData/GameData.tsx
> +        {isDealer && <img className="crud-item" src={Edit} alt="edit" />}
эта картинка - должна позволять выполнять какое-то действие. судя по дизайну это редактирование. значит пропсами должна приходит функция обработчик данного события

2021-09-17 18:31 UTC, YekaterinaKarakulina commented on src/components/Lobby/GameData/GameData.tsx
> +        <MemberCard
участник скрам мастер должен быть не захаркожен, а получаем пропсами эту инфу

2021-09-17 18:31 UTC, YekaterinaKarakulina commented on src/components/Lobby/GameData/GameData.tsx
> +            handleClick={handleSubmit}
у всех кнопок должны быть разные обработчики . кнопки exit и cancel явно не должны делать сабмит формы, а должны делать какие-то сови дейтсвия

2021-09-17 18:31 UTC, YekaterinaKarakulina commented on src/components/Lobby/GameData/GameData.tsx
> +        )}
опять же нужна  сторис для данного компонента

2021-09-17 18:31 UTC, YekaterinaKarakulina commented on src/components/Lobby/GameSettings/GameSettings.tsx
> +            <GameCard isEdit={true} />
карточки также не дожны быть захардкожены

2021-09-17 18:31 UTC, YekaterinaKarakulina commented on src/components/Lobby/GameSettings/GameSettings.tsx
> +            <GameCard isEdit={true} scoreType="sp" number="12" />
у каждой карточки есть кнопка карандашик-редактировать, значит должна передаваться к-т функция обработчик

2021-09-17 18:31 UTC, YekaterinaKarakulina commented on src/components/Lobby/GameSettings/GameSettings.tsx
> +  const [getIsTimerEnable, setIsTimerEnable] = useState(isTimerEnable);
getIsTimerEnable не может так называться - все булевские переменные называем с is.....

2021-09-17 18:31 UTC, YekaterinaKarakulina commented on src/components/Lobby/GameSettings/GameSettings.tsx
> +
Также неплохо было бы сторис для этого компонента создать

2021-09-17 18:31 UTC, YekaterinaKarakulina commented on src/components/Lobby/Issues/Issues.tsx
> +      <IssueCard title="Create new Issue" type={ETypeCard.add} />
снова все захардкожены, компонент должен получать массив объектов issues пропсами и затем мапом их отрисовать

2021-09-17 18:31 UTC, YekaterinaKarakulina commented on src/components/Lobby/Issues/Issues.tsx
> +    </div>
и сторис добавляем)

2021-09-17 18:31 UTC, YekaterinaKarakulina commented on src/components/Lobby/Members/Members.tsx
> +      {members.map((item, index) => (
вот здесь супер! компонент получает инфу пропсами. 
НО инфа на карточках захардкожена. а должна браться из элементов массива. то есть массив const members = new Array(8).fill(1); доден состоять из объектов member, содуржащих инфу, необходимую для карточки: имя фамилия и т.д.

2021-09-17 18:31 UTC, YekaterinaKarakulina commented on src/pages/Lobby/Lobby.stories.tsx
> +    <>
лишние фрагменты

2021-09-17 18:31 UTC, YekaterinaKarakulina commented on src/pages/Lobby/Lobby.stories.tsx
> +};
странная сабмит функция. посмотри как сделал Ярик в совем реквесте main Page unauthorizedю лучше вызывать какой-либо action из сторибука

2021-09-17 18:31 UTC, YekaterinaKarakulina commented on src/pages/Lobby/Lobby.stories.tsx
> +    <>
лишний фрагмент

2021-09-17 21:59 UTC, JuliaSemaka commented on src/components/Lobby/Chat/Chat.tsx
> +        <MemberCard
сделала

2021-09-17 22:29 UTC, JuliaSemaka commented on src/components/Lobby/GameData/GameData.tsx
> +          Spring 23 planning (issues 13, 533, 5623, 3252, 6623, ...)
Исправила

2021-09-17 22:29 UTC, JuliaSemaka commented on src/components/Lobby/GameData/GameData.tsx
> +        {isDealer && <img className="crud-item" src={Edit} alt="edit" />}
Исправила

2021-09-17 22:29 UTC, JuliaSemaka commented on src/components/Lobby/GameData/GameData.tsx
> +        <MemberCard
Исправила

2021-09-17 22:29 UTC, JuliaSemaka commented on src/components/Lobby/GameData/GameData.tsx
> +            handleClick={handleSubmit}
Исправила

2021-09-17 22:56 UTC, JuliaSemaka commented on src/components/Lobby/GameSettings/GameSettings.tsx
> +            <GameCard isEdit={true} />
Исправила

2021-09-17 22:56 UTC, JuliaSemaka commented on src/components/Lobby/GameSettings/GameSettings.tsx
> +            <GameCard isEdit={true} scoreType="sp" number="12" />
Исправила

2021-09-17 22:58 UTC, JuliaSemaka commented on src/components/Lobby/GameSettings/GameSettings.tsx
> +  const [getIsTimerEnable, setIsTimerEnable] = useState(isTimerEnable);
Исправила

2021-09-17 23:22 UTC, JuliaSemaka commented on src/components/Lobby/Issues/Issues.tsx
> +      <IssueCard title="Create new Issue" type={ETypeCard.add} />
Исправила

2021-09-17 23:24 UTC, JuliaSemaka commented on src/pages/Lobby/Lobby.stories.tsx
> +    <>
Исправила

2021-09-17 23:24 UTC, JuliaSemaka commented on src/pages/Lobby/Lobby.stories.tsx
> +    <>
Исправила

2021-09-17 23:25 UTC, JuliaSemaka commented on src/pages/Lobby/Lobby.stories.tsx
> +};
Это как заглушка для сторибука

2021-09-17 23:42 UTC, JuliaSemaka commented on src/components/Lobby/Members/Members.tsx
> +      {members.map((item, index) => (
Исправила

2021-09-18 13:51 UTC, JuliaSemaka commented on src/components/Lobby/Issues/Issues.tsx
> +    </div>
добавила

2021-09-18 13:51 UTC, JuliaSemaka commented on src/components/Lobby/GameData/GameData.tsx
> +        )}
добавила

2021-09-18 13:51 UTC, JuliaSemaka commented on src/components/Lobby/GameSettings/GameSettings.tsx
> +
добавила

2021-09-19 13:07 UTC, YekaterinaKarakulina requested changes

2021-09-19 13:07 UTC, YekaterinaKarakulina commented on src/components/Lobby/Chat/Chat.tsx
> +            firstName={item.userData.firstName}
Юль, давай деструктуризацию попробуем использовать

2021-09-19 13:07 UTC, YekaterinaKarakulina commented on src/components/Lobby/Chat/Chat.tsx
> +    <div className="chat-input">
наверное это должен быть тег form. и также надо добавить handleSubmit

2021-09-19 13:07 UTC, YekaterinaKarakulina commented on src/components/Lobby/GameSettings/GameSettings.tsx
> +      <form className="settings">
надо добавить onSubmit  для формы

2021-09-19 13:07 UTC, YekaterinaKarakulina commented on src/components/Lobby/Members/Members.tsx
> +          firstName={item.firstName}
деструктуризация

2021-09-19 14:01 UTC, JuliaSemaka commented on src/components/Lobby/Chat/Chat.tsx
> +            firstName={item.userData.firstName}
Исправила

2021-09-19 22:00 UTC, JuliaSemaka commented on src/components/Lobby/Chat/Chat.tsx
> +    <div className="chat-input">
исправила

2021-09-19 22:04 UTC, JuliaSemaka commented on src/components/Lobby/GameSettings/GameSettings.tsx
> +      <form className="settings">
Добавила

2021-09-19 22:06 UTC, JuliaSemaka commented on src/components/Lobby/Members/Members.tsx
> +          firstName={item.firstName}
Сделала

2021-09-20 02:27 UTC, YekaterinaKarakulina approved these changes

2021-09-20 08:24 UTC, IvanYatsko approved these changes

2021-09-20 08:27 UTC, merged