Feature/game page
JuliaSemaka/pointing-poker pull request #50
Opened 2021-09-20 13:35 UTC by JuliaSemaka

![image](https://user-images.githubusercontent.com/12410639/134011423-ae8efa5d-cb8b-435b-89ba-d7f5d75a28ce.png)

![image](https://user-images.githubusercontent.com/12410639/134011468-cd8de317-e1eb-4027-b45c-60d1e3bac2cb.png)

![image](https://user-images.githubusercontent.com/12410639/134011514-db06a3a1-9bf7-47d5-9691-0fffb503dfa3.png)

2021-09-20 17:31 UTC, YekaterinaKarakulina requested changes

2021-09-20 17:31 UTC, YekaterinaKarakulina commented on src/components/Game/Statistics/Statistics.tsx
> +  const percentTask = (number: string | null) => {
надо переименовать фцнкцию - должна начинаться с глагола

2021-09-20 17:31 UTC, YekaterinaKarakulina commented on src/components/UI/Cards/Score/Score.tsx
> +}) => {
здесь можно без фигурных скобок обойтись, сразу возвращать jsx

2021-09-20 17:31 UTC, YekaterinaKarakulina commented on src/components/Game/Issues/Issues.stories.tsx
> +export const DefaultIssues = Template.bind({});
надо переименовать сторисы дя Issues и GameData - а то у тебя эти компоненты со страницы Лобби и со страницы игры одинаково называются и сторисы перезаписывают друг друга. Назови их плиз так, чтобы было понятно что к какой странице относится - именно названия сторис)

2021-09-20 17:31 UTC, YekaterinaKarakulina commented on src/components/Game/Issues/Issues.tsx
> +              handleRunRound(
а зачем в хендлер кнопки передавать ее название?
обычно так не делают, просто пропсами приходит 2 разных обработчика handle1 и handle 2 например, и внутри компонента создается вспомогательная функция handleClickRoundButton внутри которой будет условие - проверка  какую из функций хенжлеров вызывать

2021-09-20 17:31 UTC, YekaterinaKarakulina commented on src/components/Game/Issues/Issues.tsx
> +              handleClick={() => handleRunRound('Next ISSUE')}
а здесь вооьще не понятно зачем название передавать в ф-цию обработчик

2021-09-20 17:31 UTC, YekaterinaKarakulina commented on src/components/Game/Issues/Issues.tsx
> +            number={item.number}
давай заюзаем деструктцуризацию

2021-09-20 17:31 UTC, YekaterinaKarakulina commented on src/components/Game/GameData/GameData.tsx
> +          firstName={dealerData.firstName}
деструктуризация

2021-09-20 17:31 UTC, YekaterinaKarakulina commented on src/components/Game/GameData/GameData.tsx
> +        handleClick={() => handleStopGame(isDealer ? 'Stop Game' : 'Exit')}
и здесь тоже обработчик по другому надо сделть - описывала ниже в компоненты Issues

2021-09-20 17:31 UTC, YekaterinaKarakulina commented on src/components/Game/GameData/GameData.stories.tsx
> +  .add('InputTextBigWithDefaultValue', () => (
также 2 одинаковые сторис - в Issues писала комментарий - прочти плиз там. здесь также нужно переименовать сторис - чтобы 2 сторис с разных страниц не перезаписывали друг друга

2021-09-20 19:37 UTC, JuliaSemaka commented on src/components/Game/Statistics/Statistics.tsx
> +  const percentTask = (number: string | null) => {
Исправила

2021-09-20 20:24 UTC, JuliaSemaka commented on src/components/UI/Cards/Score/Score.tsx
> +}) => {
Убрала

2021-09-20 20:30 UTC, JuliaSemaka commented on src/components/Game/Issues/Issues.stories.tsx
> +export const DefaultIssues = Template.bind({});
Переименовала

2021-09-20 20:40 UTC, JuliaSemaka commented on src/components/Game/Issues/Issues.tsx
> +              handleRunRound(
Переделала

2021-09-20 20:43 UTC, JuliaSemaka commented on src/components/Game/Issues/Issues.tsx
> +              handleClick={() => handleRunRound('Next ISSUE')}
Сделала разные ф-и обработчики

2021-09-20 20:44 UTC, JuliaSemaka commented on src/components/Game/Issues/Issues.tsx
> +            number={item.number}
сделала

2021-09-20 20:46 UTC, JuliaSemaka commented on src/components/Game/GameData/GameData.tsx
> +          firstName={dealerData.firstName}
Сделала

2021-09-20 21:31 UTC, JuliaSemaka commented on src/components/Game/GameData/GameData.tsx
> +        handleClick={() => handleStopGame(isDealer ? 'Stop Game' : 'Exit')}
Исправила

2021-09-20 21:31 UTC, JuliaSemaka commented on src/components/Game/GameData/GameData.stories.tsx
> +  .add('InputTextBigWithDefaultValue', () => (
сделала

2021-09-21 10:30 UTC, Maxfri commented on src/pages/Game/Game.tsx
> +  isDealer,
Может лучше написать {...props}, а уже внутри использовать деструктуризацию. Хотя разницы особо не будет)

2021-09-21 10:31 UTC, Maxfri approved these changes

2021-09-21 12:10 UTC, IvanYatsko approved these changes

2021-09-21 12:11 UTC, merged