feat: add component create issue
JuliaSemaka/pointing-poker pull request #51
Opened 2021-09-20 17:08 UTC by IvanYatsko

![image](https://user-images.githubusercontent.com/50986935/134044235-ec9dcbf6-e07e-4312-bf94-0c1953e9da49.png)

2021-09-20 17:38 UTC, YekaterinaKarakulina requested changes

2021-09-20 17:38 UTC, YekaterinaKarakulina commented on src/components/CreateIssueModal/CreateIssueModal.tsx
> +            handleClick={() => actionSubmit(true)}
обработчики не называем с action....
на кнопки да/нет должны быть 2 разных обработчика

2021-09-20 17:38 UTC, YekaterinaKarakulina commented on src/components/CreateIssueModal/CreateIssueModal.tsx
> +          />
handleClick={handleSubmit}

2021-09-20 17:38 UTC, YekaterinaKarakulina commented on src/components/CreateIssueModal/CreateIssueModal.tsx
> +            handleClick={() => actionSubmit(false)}
handleClick={onCancel}

2021-09-20 17:38 UTC, YekaterinaKarakulina commented on src/components/CreateIssueModal/CreateIssueModal.tsx
> +            text="Yes"
по кнопке yes происходит сабмит формы - это значит что должна быть проверка формы (валидация) и пользователь не может нажать yes пока не заполнит все поля.

2021-09-20 17:38 UTC, YekaterinaKarakulina commented on src/components/CreateIssueModal/CreateIssueModal.tsx
> +            text="No"
по кнопке No форма не сабмитится - поэтому в данном случае валидация не долждна срабатывать и модалка модет просто закрыться при нажатии этолй кнопки

2021-09-20 21:32 UTC, JuliaSemaka approved these changes

2021-09-20 21:47 UTC, IvanYatsko commented on src/components/CreateIssueModal/CreateIssueModal.tsx
> +          />
![image](https://user-images.githubusercontent.com/50986935/134079636-d3adf005-b381-491e-bd0f-89f1838c805e.png)
так ругается на типы, и чтобы не мудрить с типами, можно ли записать так?
![image](https://user-images.githubusercontent.com/50986935/134080194-c7452031-62b0-4251-9e69-85c4c71815a4.png)

2021-09-21 10:33 UTC, Maxfri commented on src/components/CreateIssueModal/CreateIssueModal.stories.tsx
> +    console.log(`Пользователь сказал: ${value}`);
Я бы убрал console.log и не понятно немного зачем тебе значение value? Если у нас при клике на Yes будет срабатывать закрытие модального окна + еще действие которое будет создавать issue, а при клике на No у нас просто будет закрываться модальное окно (возможно ещё инпуты должны очищаться).

2021-09-30 09:36 UTC, Maxfri approved these changes

2021-10-03 21:15 UTC, IvanYatsko commented on src/components/CreateIssueModal/CreateIssueModal.tsx
> +            handleClick={() => actionSubmit(true)}
исправил

2021-10-03 21:16 UTC, IvanYatsko commented on src/components/CreateIssueModal/CreateIssueModal.tsx
> +            handleClick={() => actionSubmit(false)}
исправил

2021-10-03 21:16 UTC, IvanYatsko commented on src/components/CreateIssueModal/CreateIssueModal.tsx
> +          />
исправил

2021-10-03 21:18 UTC, IvanYatsko commented on src/components/CreateIssueModal/CreateIssueModal.tsx
> +            text="No"
исправил

2021-10-03 21:19 UTC, IvanYatsko commented on src/components/CreateIssueModal/CreateIssueModal.tsx
> +            text="Yes"
исправил

2021-10-03 21:21 UTC, merged