[WIP] Implement "Connect to lobby" modal
JuliaSemaka/pointing-poker pull request #52
Opened 2021-09-21 00:47 UTC by Maxfri

1. Connect to lobby  https://github.com/JuliaSemaka/pointing-poker/issues/4
2.1 Empty
![image](https://user-images.githubusercontent.com/47328756/134095835-22639f77-926f-4915-b003-1452166663ba.png)

2.2 Fill name
![image](https://user-images.githubusercontent.com/47328756/134095853-6da43509-b58c-49d5-abcf-a689e2f06b85.png)

2.3 Fill last name
![image](https://user-images.githubusercontent.com/47328756/134095873-8c4e81b4-27ba-4948-b4f4-1ab4ff098fdd.png)

2.4 Fill job
![image](https://user-images.githubusercontent.com/47328756/134095889-37df924e-5974-4d78-9f74-709a42d1359c.png)

2.5 Fill all
![image](https://user-images.githubusercontent.com/47328756/134095908-2e3be181-3e3a-4020-83d0-e61de6c4e5bb.png)

2.6 With Upload avatar
![image](https://user-images.githubusercontent.com/47328756/134334687-0c73391a-5840-4379-a6a0-58b8a0fc930d.png)

2021-09-21 18:02 UTC, YekaterinaKarakulina requested changes
надпись "Connect as Observer" слишком прижата к заголовку формы. Сделай пожалуйста как в дизайне

форма не должна сабмититься если поля не заполнены, но нажали кнопку сабмит

2021-09-21 18:02 UTC, YekaterinaKarakulina commented on src/components/ConnectToLobby/ConnectToLobby.stories.tsx
> +  const [isCheck, setIsCheck] = useState(false);
лучше назвать isObserver setIsObserver или как-то похоже)

2021-09-21 18:02 UTC, YekaterinaKarakulina commented on src/components/ConnectToLobby/ConnectToLobby.stories.tsx
> +    <div>
див вроже как лишний во всех сторис

2021-09-21 18:02 UTC, YekaterinaKarakulina commented on src/components/ConnectToLobby/ConnectToLobby.tsx
> +              validate={[ maxLength15 ]}
давай добавим еще isRequired

2021-09-21 18:02 UTC, YekaterinaKarakulina commented on src/components/ConnectToLobby/ConnectToLobby.tsx
> +    handleStartGame,
почему такое название? любая функция , которая сабмитит форму должна называться handleSubmit
по всему файлу надо заменить

2021-09-21 18:13 UTC, YekaterinaKarakulina commented on src/components/ConnectToLobby/ConnectToLobby.stories.tsx
> +  onSubmit: action('onSubmit'),
ты здесь передаешь onSubmit , а в компоненты не принимаешь такой пропс. 
итого handleStartGame и onSubmit удаляем, оставляем 1 взамен handleSubmit

2021-09-22 14:00 UTC, JuliaSemaka approved these changes

2021-09-22 14:00 UTC, JuliaSemaka commented on src/components/ConnectToLobby/ConnectToLobby.stories.tsx
> +
Добавь App.scss, стили будут отличаться

2021-09-22 17:40 UTC, YekaterinaKarakulina approved these changes

2021-09-22 17:40 UTC, merged