Implement "Main page(unauthorized)"
JuliaSemaka/pointing-poker pull request #8
Opened 2021-09-06 15:52 UTC by Maxfri

1. Implement "Main page(unauthorized)" https://github.com/JuliaSemaka/pointing-poker/issues/3
2. Screenshot: 
2.1  Empty: 
![image](https://user-images.githubusercontent.com/47328756/132316956-c6d5d00a-f6e3-40a7-9c93-6de09d5f1a56.png)
2.2 Fill Wrong URL:  
![image](https://user-images.githubusercontent.com/47328756/132316989-5d3f116d-6112-4132-a437-f668f0923646.png)
2.3 Fill Right URL:
![image](https://user-images.githubusercontent.com/47328756/132317027-85f38727-d462-49a5-81a1-97dd6ad2f78b.png)

2021-09-06 18:53 UTC, YekaterinaKarakulina requested changes
текст ошибки должен быть красным цветом
добавить проверку инпута - что введена ссылка, а не просто текст или цифры
добавить отступы как в фигме

2021-09-06 18:53 UTC, YekaterinaKarakulina commented on src/pages/MainPage/MainPage.tsx
> +    <>
лишний фрагмент

2021-09-06 18:53 UTC, YekaterinaKarakulina commented on src/pages/MainPage/MainPage.tsx
> +  const { url } = props;
используй деструктуризацию

2021-09-06 18:53 UTC, YekaterinaKarakulina commented on src/pages/MainPage/MainPage.tsx
> +                      rules={[{ required: true, message: 'Please input your lobby URL!' }]}
Please type your lobby URL

2021-09-06 18:53 UTC, YekaterinaKarakulina commented on src/pages/MainPage/MainPage.tsx
> +                      <Input className="main-lobby-url" defaultValue={url} placeholder="Input lobby URL" />
Type lobby URL

2021-09-07 09:03 UTC, Maxfri commented on src/pages/MainPage/MainPage.tsx
> +    <>
Удалил

2021-09-07 09:03 UTC, Maxfri commented on src/pages/MainPage/MainPage.tsx
> +  const { url } = props;
Пока оставил

2021-09-07 09:04 UTC, Maxfri commented on src/pages/MainPage/MainPage.tsx
> +                      rules={[{ required: true, message: 'Please input your lobby URL!' }]}
Изменил

2021-09-07 09:04 UTC, Maxfri commented on src/pages/MainPage/MainPage.tsx
> +                      <Input className="main-lobby-url" defaultValue={url} placeholder="Input lobby URL" />
Изменил

2021-09-08 17:45 UTC, YekaterinaKarakulina commented
Ярик ссылку валидировать не нужно, у нас будет id - числовое поле. нужно сделать соответствуюшую валидацию и заменить лэйбл и плейсхолдер

2021-09-10 18:57 UTC, closed without merging